# Generated by Django 4.2.5 on 2023-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('programming_language', models.CharField(default='python/django', max_length=100)),
            ],
        ),
    ]
